version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pg-app-db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: go-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_USER: appuser
      DB_PASSWORD: secret
      DB_NAME: appdb
      DB_HOST: db
      DB_PORT: 5432
    restart: unless-stopped

volumes:
  pgdata:
